apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emberburn.tagsConfigMapName" . }}
  namespace: {{ include "emberburn.namespace" . }}
  labels:
    {{- include "emberburn.labels" . | nindent 4 }}
data:
  tags.json: |
    {{- include "emberburn.tagsConfig" . | nindent 4 }}
