{{- /*
OPC UA Server Service
Exposing 3 ports because we're extra like that
*/ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opcua-server.fullname" . }}
  labels:
    {{- include "opcua-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.opcua.port }}
    targetPort: opcua
    protocol: {{ .Values.service.opcua.protocol }}
    name: opcua
  - port: {{ .Values.service.rest.port }}
    targetPort: http
    protocol: {{ .Values.service.rest.protocol }}
    name: http
  - port: {{ .Values.service.prometheus.port }}
    targetPort: metrics
    protocol: {{ .Values.service.prometheus.protocol }}
    name: metrics
  selector:
    {{- include "opcua-server.selectorLabels" . | nindent 4 }}
